import type { NextPage } from "next";

import { ShopLayout } from "../components/layouts";

import { initialData } from "../database/products";

const Home: NextPage = () => {
  return (
    <ShopLayout
      title="Create Next App"
      pageDescription="Generated by create next app"
    >
      <h1 className="text-3xl font-bold underline">tesla shop</h1>
      <h2 className="">Todos los productos</h2>
      <div>
        {initialData.products.map((product) => (
          <div key={product.slug}>
            <p>{product.title}</p>
          </div>
        ))}
      </div>
    </ShopLayout>
  );
};

export default Home;
